<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# Function for the matrix multiplication
def mat_mul(A, B):
    row_A = len(A)
    columns_A = len(A[0])
    rows_B = len(B)
    columns_B = len(B[0])

    # To multiply  m×n matrix by an n×p matrix, the ns must be the same,
    #  the result is an m×p matrix.
    if columns_A != rows_B:
        print(
            "ERROR!.....Matrix multiplication of two arguments not possible as number of columns in first Matrix is NOT equal to the number of rows in second Matrix")
        return


    # result matrix will have dimensions of rows_A x columns_B
    # And fill the matrix with zeros
    result = [[0 for i in range(columns_B)] for j in range(row_A)]

    # Actual Logic for multiplication
    for i in range(row_A):
        for j in range(columns_B):
            for k in range(columns_A):
                # k-th column of A should be the k-th row of B
                result[i][j] += A[i][k] * B[k][j]
    return result
    #Matrix given are
A = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6]]

B = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]

A1 = [[1, 2],
      [3, 4]]

B1 = [[1, 2, 3, 4, 5],
      [5, 6, 7, 8, 9]]
A2 = [[1, 3, 4], [5, 9, 6]]

B2 = [[1, 0, 0], [0, 0, 1]]
#Display the multiplication results
print(mat_mul(A, B))
print(mat_mul(A1, B1))
print(mat_mul(A2, B2))

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
def pick_a_number_from_list(A):
    # picking an element from with the probability propotional to its magnitude
    sum = 0
    cumulative_sum = []
    for i in range(len(A)):
        sum = sum + A[i]
        cumulative_sum.append(sum)
    #compute uniform
    r = int(uniform(0, sum))
    print(r)
    number = 0
    for i in range(len(cumulative_sum)):
        if (r >= cumulative_sum[i] and r < cumulative_sum[i + 1]):
            return A[i + 1]
    return number       # return selected_random_number
        

def sampling_based_on_magnitude():
    A = [1, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    a = dict()
    print(A, sum(A))
    for i in range(1,100):
        number = pick_a_number_from_list(A)

        if number not in a:
            a[number] = 1
        else:
            a[number] += 1
    print(a)

sampling_based_on_magnitude()

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# Replace and remove all non digit  values
def replace_remove_non_digits(str):
    #Values for the replacement
    r = [
        ('\D', '',),
        ('\d', '#'),
    ]

    for o, n in r:
        str = re.sub(o, n, str)

    return str

# cases
s1 = "a2b3c4"
s2 = "234"
s3 = 'abc'
s4 = '#2a$#b%c%561#'
#print the output
print(replace_remove_non_digits(s1))
print(replace_remove_non_digits(s2))
print(replace_remove_non_digits(s3))
print(replace_remove_non_digits(s4))

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
import math
#list of students and marks of the students
Students=['studen1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

# zip will bind together students with corresponding marks as a list of tuples
grd = list(zip(Students, Marks))

grd.sort(key = lambda e: e[1])

def display_board(students, marks):
    #  for computing  top 5 students
    # Use slicing on 'grd' list of tuples
    top_5 = grd[5:]
    top = top_5[::-1]
    top_5_students = top
    #  computing top least 5 students
    least = grd[:5]
    least_5_students = least
    #  computing marks between 25th percentile and 75th percentile
    # Slice out 25th percentile and 75th percentile based on the length of the 'grades' list
    twenty_fifth = math.ceil(len(grd) // 4)
    seventy_fifth = math.floor(3 * len(grd) // 4)
    middle = grd[twenty_fifth:seventy_fifth]
    students_within_25_and_75 = middle
    
    return top_5_students, least_5_students, students_within_25_and_75
#Display the results
top_5_students, least_5_students, students_within_25_and_75 = display_board(Students, Marks)
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:


import math
# here S is list of tuples and P is a tuple of len=2
cos_list = []
S = [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
P = (3,-4)

# To find out the inverse of cosine in Python we use math.acos() function of Python Standard math Library. 
# The inverse of cosine is also called arc cosine.
for a, b in S:
  #logic for finding closet point
    nm = a * P[0] + b * P[1]
    dm = math.sqrt(a ** 2 + b ** 2) * math.sqrt(P[0] ** 2 + P[1] **2)       
    cos_list.append(math.acos(nm / dm))
#printing the outputs
X = cos_list
Y = [S for S in sorted(zip(S,X), key = lambda i: i[1])]
k = Y[:5] 
for i, j in k:
    print(i)

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math

def one(red, blue, line):
    sign_red = -1

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0:
        sign_red = 1
    #the  set of two traversal for the blue-points tuples
    for red_pt in red:
        if sign_red == 1 and eval(
                line.replace('x', '*%s' % red_pt[0]).replace('y', '*%s' % red_pt[1])) < 0:
            return 'NO'
            #compute blue point tuples
        if sign_red == -1 and eval(
                line.replace('x', '*%s' % red_pt[0]).replace('y', '*%s' % red_pt[1])) > 0:
            return 'NO'

    # Now the same set of two traversal for the blue-points tuples
    sign_blue = -1 * sign_red

    for blue_pt in blue:
        if sign_blue == 1 and eval(
                line.replace('x', '*%s' % blue_pt[0]).replace('y', '*%s' % blue_pt[1])) < 0:    
                #compute blue point tuples
            return 'NO'

        if sign_blue == -1 and eval(
                line.replace('x', '*%s' % blue_pt[0]).replace('y', '*%s' % blue_pt[1])) > 0:
            return 'NO'

    return 'YES'


Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]

Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]
#printing the outputs
for i in Lines:
    yes_or_no = one(Red, Blue, i)
    print(yes_or_no)


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
def curve_smoothing(string):
   
    list = []
#split string , is applied
    SplitStr = string.split(',')
    
    for i in range(len(SplitStr)):
        if SplitStr[i] != '_':
           list.append(i)
            
    # add the length of the original list to list
    list.append(len(SplitStr) - 1)
    
    # Loop over the list to modify the original list by filling up empty slots
    
    s = 0
    for j in list:
        # Whenever there is a missing value, add the proceeding value and the immediately next available value
        # and divide it by the number of missing values.
        # Calculate the cumulative_sum of available non-empty cells.
        value = int(SplitStr[j]) if SplitStr[j] != '_' else 0
        value += int(SplitStr[s]) if SplitStr[s] != '_' and s != j else 0

        # Divide the cumulative_sum of prev and next value by the number of missing values
        replace = value // (j - s + 1)
        SplitStr = [replace if s <= x <= j else SplitStr[x] for x in range(len(SplitStr))]
        s = j
    return SplitStr     #list of values

S =  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# function to compute conditional probabilities
def compute_cond_prob(F, S):
  #initiate numerator and denominator to 0
    nm = 0
    dm = 0
    for i in range(len(A)):
        if(A[i][1] == S):
            dm = dm + 1
            if(A[i][0] == F):
                nm = nm + 1 #increment the numerator
    print('P(F = {} | S == {}) = {}/{}'.format(F, S, str(nm), str(dm)))
    # print the output 

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

for i in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for j in ['S1', 'S2', 'S3']:
      
        compute_cond_prob(i, j)

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
def string_features(S1, S2):
    s1_unique = set(S1.split(" "))
    s2_unique = set(S2.split(" "))
    #To print number of common words s1,s2
    common_words = len(s1_unique.intersection(s2_unique)),
    #Words present in s1 but not in s2
    s1_words_not_in_s2 = s1_unique - s2_unique
    #Words present in s2 but not in s1
    s2_words_not_in_s1 = s2_unique - s1_unique

#print the output
    print('a. ', list(common_words)[0])
    print('b. ', list(s1_words_not_in_s2))
    print('b. ', list(s2_words_not_in_s1))


# Implementation
S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
string_features(S1, S2)

<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
from math import log
#imort log from math liabrary
def log_loss(A):
    crossentropy = 0   #entropy initialize to zero
    for row in A:
        #compute cross entropy
          crossentropy += (row[0] * log(row[1], 10) + ((1 - row[0]) * log(1 - row[1], 10)))
#compute log loss
    log_loss = -1 *  crossentropy / len(A)
    return log_loss

#print the output
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
print(log_loss(A))